version: '3'
services:
  app:
    build: .
    command: air
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports: 
      - "4407:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toybox_development
    cap_add:
      - SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
