version: '3'
services:
  app:
    build: .
    command: go run cmd/web/main.go
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
